FROM maven:3.8.5-openjdk-17 AS build

# Set the working directory to where pom.xml is
WORKDIR /app

# Copy only the backend/skillbridge folder to /app
COPY backend-springboot/ /app/

# Build the project
RUN mvn clean package -DskipTests

FROM openjdk:17-jdk-slim

# Copy the generated JAR file from the build stage
COPY --from=build /app/target/yumrun-food-0.0.1-SNAPSHOT.jar yumrun.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "yumrun-food-0.0.1-SNAPSHOT.jar"]
